import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Card } from "@/components/Card";
import { Nav } from "@/components/Nav";
import { queryDatabase } from "@/lib/notion";

export default function Home({ database }) {
  const navItems = ["Users", "Create Post"];
  return (
    <>
      <Head>
        <title>Notion testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav items={navItems} />
        <section>
          <h2>Blog posts</h2>
          {database.map((d, i) => (
            <ul className="cards" key={i}>
              <li>
                <Link href={`/page/${d.id}`}>
                  <Card {...d} />
                </Link>
              </li>
            </ul>
          ))}
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const databaseId = process.env.NOTION_DATABASE_ID;
  const database = await queryDatabase(databaseId);

  return {
    props: {
      database,
    },
  };
}
