import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Card } from "@/components/Card";
import { Nav } from "@/components/Nav";
import { queryDatabase, sortDatabase } from "@/lib/notion";
import { useState } from "react";

export default function Home({ database }) {
  const [sortedDatabase, setSortedDatabase] = useState(null);

  const navItems = ["Users", "Create Post"];
  const onChange = async (e) => {
    const sortType = e.target.value;
    const list = await sortDatabase(sortType);
    setSortedDatabase(list.response.results);
  };

  return (
    <>
      <Head>
        <title>Notion testing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav items={navItems} />
        <section>
          <h2>Blog posts</h2>
          <label for="sort">Sort blog posts:</label>
          <select onChange={onChange} name="sort" id="sort">
            <option selected disabled>
              Options
            </option>
            <option value="ascending">Ascending</option>
            <option value="descending">Descending</option>
          </select>
          <ul className="cards">
            {(sortedDatabase || database).map((d, i) => (
              <li key={i}>
                <Link href={`/page/${d.id}`}>
                  <Card {...d} />
                </Link>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const databaseId = process.env.NOTION_DATABASE_ID;
  const database = await queryDatabase(databaseId);

  return {
    props: {
      database,
    },
  };
}
